code --install-extension EditorConfig.EditorConfig
code --install-extension HookyQR.beautify
code --install-extension PeterJausovec.vscode-docker
code --install-extension WakaTime.vscode-wakatime
code --install-extension abusaidm.html-snippets
code --install-extension alefragnani.Bookmarks
code --install-extension christian-kohler.path-intellisense
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension ms-vscode.atom-keybindings
code --install-extension ms-vscode.Theme-MarkdownKit
code --install-extension nemesarial.dust
code --install-extension nepaul.editorconfiggenerator
code --install-extension qezhu.gitlink
code --install-extension robertohuertasm.vscode-icons
code --install-extension sysoev.language-stylus
code --install-extension vscodevim.vim
code --install-extension waderyan.gitblame