apm install file-icons
apm install atom-beautify
apm install linter 
apm install vim-mode-plus
apm install highlight-selected
#apm install language-mustache
apm install stylus
apm install language-docker
apm install git-plus
apm install terminal-plus
